MAKEFILEDIR = /NextDeveloper/Makefiles/driverkit
MAKEFILE = Makefile.main_driver
LOCALMAKEFILEDIR = /LocalDeveloper/Makefiles/driverkit
LOCALMAKEFILE = Makefile.local_preamble
-include $(LOCALMAKEFILEDIR)/$(LOCALMAKEFILE)
