# OSMGAService_reloc - generated MiG server plus P2.0 implementation.

NAME = OSMGAService_reloc

PROJECTVERSION = 0.2
LANGUAGE = English

CLASSES = OpenStepMGAService.m
CFILES = OpenStepMGAServer.c
HFILES = OpenStepMGAProtocol.h
OTHERSRCS = Makefile Makefile.preamble Makefile.postamble\
            Makefile.driver_preamble Load_Commands.sect Unload_Commands.sect\
            OpenStepMGA.defs

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make
SOURCEMODE = 444

-include Makefile.preamble
include $(MAKEFILEDIR)/$(MAKEFILE)
-include Makefile.postamble
-include Makefile.dependencies
