#
# OpenStepMGAReplacementDisplay - R4 staging bundle only.
#

NAME = OpenStepMGAReplacementDisplay

PROJECTVERSION = 0.1
LANGUAGE = English

LOCAL_RESOURCES = Localizable.strings
GLOBAL_RESOURCES = Default.table
TOOLS = OpenStepMGAReplacementDisplay_reloc.tproj

OTHERSRCS = Makefile Makefile.preamble Makefile.postamble README.md

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = bundle.make
SOURCEMODE = 444
BUNDLE_EXTENSION = config

-include Makefile.preamble
include $(MAKEFILEDIR)/$(MAKEFILE)
-include Makefile.postamble
-include Makefile.dependencies
