#!/usr/bin/env python3
"""extract-warp-ucode.py - generate OpenStepMGAWarpUcode.{h,c} from the
X.Org MGA driver's mga_ucode.h.

    python3 warp/extract-warp-ucode.py <path/to/mga_ucode.h> <out-dir>

Only the sixteen G400 pipes are taken.  The eight G200 ones are 11,776
bytes this card can never run: the driver binds device 0x0525 at G450-class
revisions only.

The upstream file is MIT-licensed ((c) 1999 Matrox Graphics Inc.); its
notice is copied verbatim into the generated .c, which is the condition of
using it.

Pipe numbering is a bit combination, not a sequence: F=1, A=2, S=4, T2=8
(mga_drm.h).  The install order in mga_warp_install_g400_microcode happens
to be exactly 0..15, but the *sizes* are not uniform -- 1024 bytes for
pipes 0-7 against 1280 for 8-15 -- so offsets accumulate rather than being
computed from the index.
"""
import re
import sys

UCODE, OUT = sys.argv[1:3]

F, A, S, T2 = 1, 2, 4, 8
PIPES = [
    ("tgz",     0),          ("tgzf",    F),        ("tgza",    A),
    ("tgzaf",   F | A),      ("tgzs",    S),        ("tgzsf",   S | F),
    ("tgzsa",   S | A),      ("tgzsaf",  S | F | A),
    ("t2gz",    T2),         ("t2gzf",   T2 | F),   ("t2gza",   T2 | A),
    ("t2gzaf",  T2 | A | F), ("t2gzs",   T2 | S),   ("t2gzsf",  T2 | S | F),
    ("t2gzsa",  T2 | S | A), ("t2gzsaf", T2 | S | F | A),
]
ALIGN = 256

src = open(UCODE).read()

notice = src[src.index("/*"):src.index("*/") + 2]
assert "Permission is hereby granted" in notice, "upstream notice not found"

arrays = {}
for m in re.finditer(r'unsigned char (WARP_G400_(\w+))\[\]\s*=\s*\{(.*?)\}\s*;',
                     src, re.S):
    arrays[m.group(2)] = [int(v, 16)
                          for v in re.findall(r'0x([0-9a-fA-F]+)', m.group(3))]

missing = [n for n, _ in PIPES if n not in arrays]
if missing:
    raise SystemExit("missing G400 pipes in %s: %s" % (UCODE, missing))


def aligned(n):
    return (n // ALIGN + 1) * ALIGN


total = sum(aligned(len(arrays[n])) for n, _ in PIPES)

with open(OUT + "/OpenStepMGAWarpUcode.c", "w") as f:
    f.write("/*\n * OpenStepMGAWarpUcode.c - WARP microcode for the Matrox\n"
            " * G400/G450 pipes, generated by warp/extract-warp-ucode.py from\n"
            " * the X.Org MGA driver's mga_ucode.h.  Do not edit by hand.\n"
            " *\n * Upstream notice, reproduced as required:\n */\n\n")
    f.write(notice)
    f.write("\n\n#import \"OpenStepMGAWarpUcode.h\"\n\n")
    for name, _ in PIPES:
        data = arrays[name]
        f.write("static const unsigned char osmgaWarpG400_%s[%d] = {\n"
                % (name, len(data)))
        for i in range(0, len(data), 12):
            f.write("    " + " ".join("0x%02X," % b for b in data[i:i + 12])
                    + "\n")
        f.write("};\n\n")
    f.write("/* Indexed by pipe number (F=1 A=2 S=4 T2=8), not by install\n"
            " * order.  They coincide here, but the sizes do not, so callers\n"
            " * must accumulate offsets instead of scaling the index. */\n")
    f.write("const OSMGAWarpPipe osmgaWarpG400Pipes[OSMGA_WARP_PIPES] = {\n")
    for name, idx in sorted(PIPES, key=lambda p: p[1]):
        f.write("    { osmgaWarpG400_%s, %dUL },   /* %2d %s */\n"
                % (name, len(arrays[name]), idx, name))
    f.write("};\n")

with open(OUT + "/OpenStepMGAWarpUcode.h", "w") as f:
    f.write("""/*
 * OpenStepMGAWarpUcode.h - see OpenStepMGAWarpUcode.c.  Generated by
 * warp/extract-warp-ucode.py; do not edit by hand.
 */
#ifndef OPENSTEP_MGA_WARP_UCODE_H
#define OPENSTEP_MGA_WARP_UCODE_H

#define OSMGA_WARP_PIPES        16
#define OSMGA_WARP_ALIGN        %d

/* Sum of every pipe rounded up to OSMGA_WARP_ALIGN, which is what the
 * hardware layout costs.  Note the rounding adds a full block even when a
 * pipe is already a multiple of the alignment, matching the DRM. */
#define OSMGA_WARP_TOTAL_BYTES  %dUL

typedef struct {
    const unsigned char *bytes;
    unsigned long        length;
} OSMGAWarpPipe;

extern const OSMGAWarpPipe osmgaWarpG400Pipes[OSMGA_WARP_PIPES];

#endif /* OPENSTEP_MGA_WARP_UCODE_H */
""" % (ALIGN, total))

print("pipes   : %d" % len(PIPES))
print("raw     : %d bytes" % sum(len(arrays[n]) for n, _ in PIPES))
print("aligned : %d bytes" % total)
