/*
 * OpenStepMGAWarpUcode.h - see OpenStepMGAWarpUcode.c.  Generated by
 * warp/extract-warp-ucode.py; do not edit by hand.
 */
#ifndef OPENSTEP_MGA_WARP_UCODE_H
#define OPENSTEP_MGA_WARP_UCODE_H

#define OSMGA_WARP_PIPES        16
#define OSMGA_WARP_ALIGN        256

/* Sum of every pipe rounded up to OSMGA_WARP_ALIGN, which is what the
 * hardware layout costs.  Note the rounding adds a full block even when a
 * pipe is already a multiple of the alignment, matching the DRM. */
#define OSMGA_WARP_TOTAL_BYTES  18432UL

typedef struct {
    const unsigned char *bytes;
    unsigned long        length;
} OSMGAWarpPipe;

extern const OSMGAWarpPipe osmgaWarpG400Pipes[OSMGA_WARP_PIPES];

#endif /* OPENSTEP_MGA_WARP_UCODE_H */
